baseURL = "https://alfredoroca.bitbucket.io"
languageCode = "en-us"
theme = "temple"
title = "Alfredo's Blog"
[author]
github = "AlfredoRoca"
name = "Alfredo Roca"
[params]
favicon = ""
highlight = true
hjslangs = ["go", "vim", "ruby", "bash"]
topmenu = "categories"
[taxonomies]
category = "categories"
tag = "tags"
