baseURL = "https://alfredoroca.bitbucket.io"
languageCode = "en-us"
title = "Alfredo's Blog"
theme = "temple"

[params]
  favicon = ""

  # Enables syntax highlighting
  highlight = true 

  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for what's included in original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim", "ruby", "bash"]

  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Alfredo Roca"
  github = "AlfredoRoca"
