---
pages:
- posts/postman-tests-sample.md
- posts/fast-group-and-count-in-rails.md
- posts/how-to-get-a-class-instance-from-a-variable-in-ruby.md
- posts/list-affected-files-in-a-git-branch.md
- posts/duplicate-hash-in-ruby.md
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
