---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- posts/list-affected-files-in-a-git-branch.md
- posts/fast-group-and-count-in-rails.md
- posts/rails-debug-to-stderror.md
- posts/how--display-flex--or--display--grid--redefines-what--margin--auto--does-on-top-and-bottom--allowing-for-vertical-centering.md
- posts/sublime-shortcuts.md
- posts/equal-height-rows-with-css.md
- posts/devise-mailer-layout.md
- posts/git-tagging.md
- posts/image-from-rails-assets-collection.md
- posts/include-helper-in-devise-custom-mailer.md
- posts/selfsigned-ssl-certificate-for-develpment.md
- posts/odoo-workflow.md
- posts/odoo-workflow-for-saleorder.md
- posts/monit-installation-process.md
- posts/issue-with-audio-in-linux-fedora-26.md
- posts/install-gems-locally-to-project-in-rails.md
- posts/swagger-blocks-response-with-json-object.md
- posts/callback-conditional-to-only-some-fields-changes.md
- posts/compare-files-in-different-branches.md
- posts/duplicate-hash-in-ruby.md
- posts/git-difference-between-branches.md
- posts/how-to-get-a-class-instance-from-a-variable-in-ruby.md
- posts/postman-tests-sample.md
- posts/rails-migration-to-remove-or-change-column-default-value.md
- posts/rails--create-has_one-association-with-custom-column-type-and-name.md
- posts/resolve-merge-conflict-with-git.md
- posts/ruby-toggle-or-items-ring.md
